export const GRBL_DESCRIPTIONS = {
    "$0": "Step pulse time in microseconds",
    "$1": "Step idle delay in milliseconds",
    "$2": "Step pulse invert mask",
    "$3": "Step direction invert mask",
    "$4": "Invert step enable pin",
    "$5": "Invert limit pins",
    "$6": "Invert probe pin",
    "$10": "Status report options mask",
    "$11": "Junction deviation in millimeters",
    "$12": "Arc tolerance in millimeters",
    "$13": "Report in inches",
    "$20": "Soft limits enabled",
    "$21": "Hard limits enabled",
    "$22": "Homing cycle enabled",
    "$23": "Homing direction invert mask",
    "$24": "Homing feed rate in mm/min",
    "$25": "Homing seek rate in mm/min",
    "$26": "Homing debounce delay in milliseconds",
    "$27": "Homing pull-off in millimeters",
    "$30": "Maximum spindle speed in RPM",
    "$31": "Minimum spindle speed in RPM",
    "$32": "Laser mode enabled",
    "$100": "X-axis steps per millimeter",
    "$101": "Y-axis steps per millimeter",
    "$102": "Z-axis steps per millimeter",
    "$110": "X-axis maximum rate in mm/min",
    "$111": "Y-axis maximum rate in mm/min",
    "$112": "Z-axis maximum rate in mm/min",
    "$120": "X-axis acceleration in mm/sec²",
    "$121": "Y-axis acceleration in mm/sec²",
    "$122": "Z-axis acceleration in mm/sec²",
    "$130": "X-axis maximum travel in millimeters",
    "$131": "Y-axis maximum travel in millimeters",
    "$132": "Z-axis maximum travel in millimeters"
};